# Configuration file for Beckhoff EL1859
vendor_id: 0x00000002
product_id: 0x07433052

rpdo:  # RxPDO
  - index: 0x1608
    channels:
    - {index: 0x7080, sub_index: 1, type: bool, mask: 1, command_interface: do0}
  - index: 0x1609
    channels:
    - {index: 0x7090, sub_index: 1, type: bool, mask: 2, command_interface: do1}
  - index: 0x160a
    channels:
    - {index: 0x70a0, sub_index: 1, type: bool, mask: 4, command_interface: do2}
  - index: 0x160b
    channels:
    - {index: 0x70b0, sub_index: 1, type: bool, mask: 8, command_interface: do3}
  - index: 0x160c
    channels:
    - {index: 0x70c0, sub_index: 1, type: bool, mask: 16, command_interface: do4}
  - index: 0x160d
    channels:
    - {index: 0x70d0, sub_index: 1, type: bool, mask: 32, command_interface: do5}
  - index: 0x160e
    channels:
    - {index: 0x70e0, sub_index: 1, type: bool, mask: 64, command_interface: do6}
  - index: 0x160f
    channels:
    - {index: 0x70f0, sub_index: 1, type: bool, mask: 128, command_interface: do7}


tpdo:  # TxPDO
  - index: 0x1a00
    channels:
      - {index: 0x6000, sub_index: 1, type: bool, mask: 1, state_interface: di0}
  - index: 0x1a01
    channels:
      - {index: 0x6010, sub_index: 1, type: bool, mask: 2, state_interface: di1}
  - index: 0x1a02
    channels:
      - {index: 0x6020, sub_index: 1, type: bool, mask: 4, state_interface: di2}
  - index: 0x1a03
    channels:
      - {index: 0x6030, sub_index: 1, type: bool, mask: 8, state_interface: di3}
  - index: 0x1a04
    channels:
      - {index: 0x6040, sub_index: 1, type: bool, mask: 16, state_interface: di4}
  - index: 0x1a05
    channels:
      - {index: 0x6050, sub_index: 1, type: bool, mask: 32, state_interface: di5}
  - index: 0x1a06
    channels:
      - {index: 0x6060, sub_index: 1, type: bool, mask: 64, state_interface: di6}
  - index: 0x1a07
    channels:
      - {index: 0x6070, sub_index: 1, type: bool, mask: 128, state_interface: di7}

sm:  # Sync Manager
  - {index: 2, type: output, pdo: rpdo, watchdog: disable}
  - {index: 3, type: input,  pdo: tpdo, watchdog: disable}
