vendor_id: 0x00000002
product_id: 0x0d173052


tpdo:
  - index: 0x1A00
    channels:
      - {index: 0x6000, sub_index: 0x0001, type: bool, state_interface: underrange, factor: 1.0}  #Underrange
      - {index: 0x6000, sub_index: 0x0002, type: bool, state_interface: overange, factor: 1.0}  #Overrange
      - {index: 0x6000, sub_index: 0x0007, type: bool, state_interface: error, factor: 1.0}  #Error
      - {index: 0x1800, sub_index: 0x0007, type: bool, state_interface: unknown, factor: 1.0}  #TxPDO State
      - {index: 0x1800, sub_index: 0x0009, type: bool, state_interface: unknown, factor: 1.0}  #TxPDO Toggle
      - {index: 0x6000, sub_index: 0x0011, type: int32, state_interface: value, factor: 1.0}  #Value
  - index: 0x1A01
    channels:
      - {index: 0x6010, sub_index: 0x0001, type: bool, state_interface: unknown, factor: 1.0}  #Underrange
      - {index: 0x6010, sub_index: 0x0002, type: bool, state_interface: unknown, factor: 1.0}  #Overrange
      - {index: 0x6010, sub_index: 0x0007, type: bool, state_interface: unknown, factor: 1.0}  #Error
      - {index: 0x1801, sub_index: 0x0007, type: bool, state_interface: unknown, factor: 1.0}  #TxPDO State
      - {index: 0x1801, sub_index: 0x0009, type: bool, state_interface: unknown, factor: 1.0}  #TxPDO Toggle
      - {index: 0x6010, sub_index: 0x0011, type: int32, state_interface: value2, factor: 1.0}  #Value


sm:  # Sync Manager
#  - {index: 2, type: output, pdo: ~, watchdog: disable}
  - {index: 3, type: input,  pdo: tpdo, watchdog: disable}
