# Configuration file for EL7201 drive

vendor_id: 0x00000002
product_id: 0x1c213052
assign_activate: 0x0700  # DC Synch register
sdo:
  - {index: 0x7010, sub_index: 0x0003, type: uint8, value: 8}  # Modes of operation
  - {index: 0x7010, sub_index: 0x000B, type: uint16, value: 2952}  # DRV Outputs / Torque limitation
  - {index: 0x8000, sub_index: 0x0001, type: uint8, value: 0}  # FB Settings / Invert feedback direction
  - {index: 0x8010, sub_index: 0x0012, type: uint16, value: 5}  # DRV Amplifier Settings / Current loop integral time
  - {index: 0x8010, sub_index: 0x0013, type: uint16, value: 178}  # DRV Amplifier Settings / Current loop proportional gain
  - {index: 0x8010, sub_index: 0x0014, type: uint32, value: 150}  # DRV Amplifier Settings / Velocity loop integral time
  - {index: 0x8010, sub_index: 0x0015, type: uint32, value: 43}  # DRV Amplifier Settings / Velocity loop proportional gain
  - {index: 0x8010, sub_index: 0x0017, type: uint32, value: 10}  # Position loop proportional gain
  - {index: 0x8010, sub_index: 0x0019, type: uint32, value: 24000}  # Nominal DC link voltage
  - {index: 0x8010, sub_index: 0x0031, type: uint32, value: 262144}  # Velocity limitation
  - {index: 0x8011, sub_index: 0x0011, type: uint32, value: 8600}  # DRV Motor Settings / Max current
  - {index: 0x8011, sub_index: 0x0012, type: uint32, value: 2710}  # DRV Motor Settings / Rated current
  - {index: 0x8011, sub_index: 0x0013, type: uint8, value: 3}  # DRV Motor Settings / Motor pole pairs
  - {index: 0x8011, sub_index: 0x0015, type: uint16, value: 270}  # DRV Motor Settings / Commutation offset
  - {index: 0x8011, sub_index: 0x0016, type: uint32, value: 70}  # DRV Motor Settings / Torque constant
  - {index: 0x8011, sub_index: 0x0018, type: uint32, value: 34}  # DRV Motor Settings / Rotor moment of inertia
  - {index: 0x8011, sub_index: 0x0019, type: uint16, value: 15}  # DRV Motor Settings / Winding inductance
  - {index: 0x8011, sub_index: 0x001B, type: uint32, value: 1961}  # DRV Motor Settings / Motor speed limitation
  - {index: 0x8011, sub_index: 0x002B, type: uint16, value: 1200}  # DRV Motor Settings / Motor Temperature warn level
  - {index: 0x8011, sub_index: 0x002C, type: uint16, value: 1400}  # DRV Motor Settings / Motor Temperature error level
  - {index: 0x8011, sub_index: 0x002D, type: uint16, value: 341}  # DRV Motor Settings / Motor thermal time constant
rpdo:
  - index: 0x1600
    channels:
      - {index: 0x7010, sub_index: 0x0001, type: uint16, command_interface: ctrl_word, default: 0}  #Controlword
  - index: 0x1606
    channels:
      - {index: 0x7010, sub_index: 0x0005, type: uint32, command_interface: position, default: 0}  #Target position
  - index: 0x1608
    channels:
      - {index: 0x7010, sub_index: 0x0003, type: uint8, command_interface: moo, default: 8}  #Modes of operation
tpdo:
  - index: 0x1A00
    channels:
      - {index: 0x6000, sub_index: 0x0011, type: uint32, state_interface: position, factor: 1.0}  #Position
  - index: 0x1A01
    channels:
      - {index: 0x6010, sub_index: 0x0001, type: uint16, state_interface: status_word}  #Statusword
  - index: 0x1A02
    channels:
      - {index: 0x6010, sub_index: 0x0007, type: int32, state_interface: velocity, factor: 1.0}  #Velocity actual value
  - index: 0x1A03
    channels:
      - {index: 0x6010, sub_index: 0x0008, type: int16, state_interface: effort, factor: 1.0}  #Torque actual value
  - index: 0x1A06
    channels:
      - {index: 0x6010, sub_index: 0x0006, type: int32, state_interface: following_error, factor: 1.0}  #Following error actual value
  - index: 0x1A0E
    channels:
      - {index: 0x6010, sub_index: 0x0003, type: uint8, state_interface: moo_display, factor: 1.0}  #Modes of operation display

available_rpdo:
  - index: 0x1601
    channels:
      - {index: 0x7010, sub_index: 0x0006, type: int32, command_interface: unknown, default: .nan}  #Target velocity
  - index: 0x1602
    channels:
      - {index: 0x7010, sub_index: 0x0009, type: int16, command_interface: unknown, default: .nan}  #Target torque
  - index: 0x1603
    channels:
      - {index: 0x7010, sub_index: 0x000E, type: uint16, command_interface: unknown, default: .nan}  #Commutation angle
  - index: 0x1604
    channels:
      - {index: 0x7010, sub_index: 0x000B, type: uint16, command_interface: unknown, default: .nan}  #Torque limitation
  - index: 0x1605
    channels:
      - {index: 0x7010, sub_index: 0x000A, type: int16, command_interface: unknown, default: .nan}  #Torque offset
  - index: 0x1607
    channels:
      - {index: 0x7001, sub_index: 0x0001, type: bool, command_interface: unknown, default: .nan}  #Touch probe function__TP1 Enable
      - {index: 0x7001, sub_index: 0x0002, type: bool, command_interface: unknown, default: .nan}  #Touch probe function__TP1 Continous
      - {index: 0x7001, sub_index: 0x0003, type: uint2, command_interface: unknown, default: .nan}  #Touch probe function__TP1 Trigger mode
      - {index: 0x7001, sub_index: 0x0005, type: bool, command_interface: unknown, default: .nan}  #Touch probe function__TP1 Enable pos edge
      - {index: 0x7001, sub_index: 0x0006, type: bool, command_interface: unknown, default: .nan}  #Touch probe function__TP1 Enable neg edge
      - {index: 0x7001, sub_index: 0x0009, type: bool, command_interface: unknown, default: .nan}  #Touch probe function__TP2 Enable
      - {index: 0x7001, sub_index: 0x000A, type: bool, command_interface: unknown, default: .nan}  #Touch probe function__TP2 Continous
      - {index: 0x7001, sub_index: 0x000B, type: uint2, command_interface: unknown, default: .nan}  #Touch probe function__TP2 Trigger mode
      - {index: 0x7001, sub_index: 0x000D, type: bool, command_interface: unknown, default: .nan}  #Touch probe function__TP2 Enable pos edge
      - {index: 0x7001, sub_index: 0x000E, type: bool, command_interface: unknown, default: .nan}  #Touch probe function__TP2 Enable neg edge
  - index: 0x1630
    channels:
      - {index: 0x7030, sub_index: 0x0002, type: bool, command_interface: unknown, default: 0}  #DMC__FeedbackControl__Enable latch extern on positive edge
      - {index: 0x7030, sub_index: 0x0003, type: bool, command_interface: unknown, default: 0}  #DMC__FeedbackControl__Set counter
      - {index: 0x7030, sub_index: 0x0004, type: bool, command_interface: unknown, default: 0}  #DMC__FeedbackControl__Enable latch extern on negative edge
      - {index: 0x7030, sub_index: 0x0011, type: bool, command_interface: unknown, default: 0}  #DMC__DriveControl__Enable
      - {index: 0x7030, sub_index: 0x0012, type: bool, command_interface: unknown, default: 0}  #DMC__DriveControl__Reset
      - {index: 0x7030, sub_index: 0x0021, type: bool, command_interface: unknown, default: 0}  #DMC__PositioningControl__Execute
      - {index: 0x7030, sub_index: 0x0022, type: bool, command_interface: unknown, default: 0}  #DMC__PositioningControl__Emergency stop
      - {index: 0x7030, sub_index: 0x0031, type: int64, command_interface: unknown, default: .nan}  #DMC__Set counter value
      - {index: 0x7030, sub_index: 0x0032, type: int64, command_interface: unknown, default: .nan}  #DMC__Target position
      - {index: 0x7030, sub_index: 0x0033, type: int16, command_interface: unknown, default: .nan}  #DMC__Target velocity
      - {index: 0x7030, sub_index: 0x0034, type: uint16, command_interface: unknown, default: .nan}  #DMC__Start type
      - {index: 0x7030, sub_index: 0x0035, type: uint16, command_interface: unknown, default: .nan}  #DMC__Target acceleration
      - {index: 0x7030, sub_index: 0x0036, type: uint16, command_interface: unknown, default: .nan}  #DMC__Target deceleration
  - index: 0x1631
    channels:
      - {index: 0x7030, sub_index: 0x0002, type: bool, command_interface: unknown, default: 0}  #DMC__FeedbackControl__Enable latch extern on positive edge
      - {index: 0x7030, sub_index: 0x0003, type: bool, command_interface: unknown, default: 0}  #DMC__FeedbackControl__Set counter
      - {index: 0x7030, sub_index: 0x0004, type: bool, command_interface: unknown, default: 0}  #DMC__FeedbackControl__Enable latch extern on negative edge
      - {index: 0x7030, sub_index: 0x0011, type: bool, command_interface: unknown, default: 0}  #DMC__DriveControl__Enable
      - {index: 0x7030, sub_index: 0x0012, type: bool, command_interface: unknown, default: 0}  #DMC__DriveControl__Reset
      - {index: 0x7030, sub_index: 0x0021, type: bool, command_interface: unknown, default: 0}  #DMC__PositioningControl__Execute
      - {index: 0x7030, sub_index: 0x0022, type: bool, command_interface: unknown, default: 0}  #DMC__PositioningControl__Emergency stop
      - {index: 0x7030, sub_index: 0x0031, type: int32, command_interface: unknown, default: .nan}  #DMC__Set counter value
      - {index: 0x7030, sub_index: 0x0032, type: int32, command_interface: unknown, default: .nan}  #DMC__Target position
      - {index: 0x7030, sub_index: 0x0033, type: int16, command_interface: unknown, default: .nan}  #DMC__Target velocity
      - {index: 0x7030, sub_index: 0x0034, type: uint16, command_interface: unknown, default: .nan}  #DMC__Start type
      - {index: 0x7030, sub_index: 0x0035, type: uint16, command_interface: unknown, default: .nan}  #DMC__Target acceleration
      - {index: 0x7030, sub_index: 0x0036, type: uint16, command_interface: unknown, default: .nan}  #DMC__Target deceleration

available_tpdo:
  - index: 0x1A02
    channels:
      - {index: 0x6010, sub_index: 0x0007, type: int32, state_interface: unknown, factor: 1.0}  #Velocity actual value
  - index: 0x1A03
    channels:
      - {index: 0x6010, sub_index: 0x0008, type: int16, state_interface: unknown, factor: 1.0}  #Torque actual value
  - index: 0x1A04
    channels:
      - {index: 0x6010, sub_index: 0x0012, type: uint16, state_interface: unknown, factor: 1.0}  #Info data 1
  - index: 0x1A05
    channels:
      - {index: 0x6010, sub_index: 0x0013, type: uint16, state_interface: unknown, factor: 1.0}  #Info data 2
  - index: 0x1A07
    channels:
      - {index: 0x6001, sub_index: 0x0001, type: bool, state_interface: unknown, factor: 1.0}  #Touch probe status__TP1 Enable
      - {index: 0x6001, sub_index: 0x0002, type: bool, state_interface: unknown, factor: 1.0}  #Touch probe status__TP1 Pos value stored
      - {index: 0x6001, sub_index: 0x0003, type: bool, state_interface: unknown, factor: 1.0}  #Touch probe status__TP1 Neg value stored
      - {index: 0x6001, sub_index: 0x0008, type: bool, state_interface: unknown, factor: 1.0}  #Touch probe status__TP1 Input
      - {index: 0x6001, sub_index: 0x0009, type: bool, state_interface: unknown, factor: 1.0}  #Touch probe status__TP2 Enable
      - {index: 0x6001, sub_index: 0x000A, type: bool, state_interface: unknown, factor: 1.0}  #Touch probe status__TP2 Pos value stored
      - {index: 0x6001, sub_index: 0x000B, type: bool, state_interface: unknown, factor: 1.0}  #Touch probe status__TP2 Neg value stored
      - {index: 0x6001, sub_index: 0x0010, type: bool, state_interface: unknown, factor: 1.0}  #Touch probe status__TP2 Input
  - index: 0x1A08
    channels:
      - {index: 0x6001, sub_index: 0x0011, type: uint32, state_interface: unknown, factor: 1.0}  #TP1 Pos position
  - index: 0x1A09
    channels:
      - {index: 0x6001, sub_index: 0x0012, type: uint32, state_interface: unknown, factor: 1.0}  #TP1 Neg position
  - index: 0x1A0A
    channels:
      - {index: 0x6001, sub_index: 0x0013, type: uint32, state_interface: unknown, factor: 1.0}  #TP2 Pos position
  - index: 0x1A0B
    channels:
      - {index: 0x6001, sub_index: 0x0014, type: uint32, state_interface: unknown, factor: 1.0}  #TP2 Neg position
  - index: 0x1A0C
    channels:
      - {index: 0x6000, sub_index: 0x000E, type: bool, state_interface: unknown, factor: 1.0}  #Status__TxPDO State
      - {index: 0x6000, sub_index: 0x000F, type: uint2, state_interface: unknown, factor: 1.0}  #Status__Input Cycle Counter
  - index: 0x1A30
    channels:
      - {index: 0x6030, sub_index: 0x0002, type: bool, state_interface: unknown, factor: 1.0}  #DMC__FeedbackStatus__Latch extern valid
      - {index: 0x6030, sub_index: 0x0003, type: bool, state_interface: unknown, factor: 1.0}  #DMC__FeedbackStatus__Set counter done
      - {index: 0x6030, sub_index: 0x000D, type: bool, state_interface: unknown, factor: 1.0}  #DMC__FeedbackStatus__Status of extern latch
      - {index: 0x6030, sub_index: 0x0011, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Ready to enable
      - {index: 0x6030, sub_index: 0x0012, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Ready
      - {index: 0x6030, sub_index: 0x0013, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Warning
      - {index: 0x6030, sub_index: 0x0014, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Error
      - {index: 0x6030, sub_index: 0x0015, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Moving positive
      - {index: 0x6030, sub_index: 0x0016, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Moving negative
      - {index: 0x6030, sub_index: 0x001C, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Digital input 1
      - {index: 0x6030, sub_index: 0x001D, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Digital input 2
      - {index: 0x6030, sub_index: 0x0021, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Busy
      - {index: 0x6030, sub_index: 0x0022, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__In-Target
      - {index: 0x6030, sub_index: 0x0023, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Warning
      - {index: 0x6030, sub_index: 0x0024, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Error
      - {index: 0x6030, sub_index: 0x0025, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Calibrated
      - {index: 0x6030, sub_index: 0x0026, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Accelerate
      - {index: 0x6030, sub_index: 0x0027, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Decelerate
      - {index: 0x6030, sub_index: 0x0028, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Ready to execute
      - {index: 0x6030, sub_index: 0x0031, type: int64, state_interface: unknown, factor: 1.0}  #DMC__Set position
      - {index: 0x6030, sub_index: 0x0032, type: int16, state_interface: unknown, factor: 1.0}  #DMC__Set velocity
      - {index: 0x6030, sub_index: 0x0033, type: uint32, state_interface: unknown, factor: 1.0}  #DMC__Actual drive time
      - {index: 0x6030, sub_index: 0x0034, type: int64, state_interface: unknown, factor: 1.0}  #DMC__Actual position lag
      - {index: 0x6030, sub_index: 0x0035, type: int16, state_interface: unknown, factor: 1.0}  #DMC__Actual velocity
      - {index: 0x6030, sub_index: 0x0036, type: int64, state_interface: unknown, factor: 1.0}  #DMC__Actual position
      - {index: 0x6030, sub_index: 0x0037, type: uint32, state_interface: unknown, factor: 1.0}  #DMC__Error id
      - {index: 0x6030, sub_index: 0x0038, type: uint8, state_interface: unknown, factor: 1.0}  #DMC__Input cycle counter
      - {index: 0x6030, sub_index: 0x003A, type: int64, state_interface: unknown, factor: 1.0}  #DMC__Latch value
      - {index: 0x6030, sub_index: 0x003B, type: int16, state_interface: unknown, factor: 1.0}  #DMC__Cyclic info data 1
      - {index: 0x6030, sub_index: 0x003C, type: int16, state_interface: unknown, factor: 1.0}  #DMC__Cyclic info data 2
  - index: 0x1A31
    channels:
      - {index: 0x6030, sub_index: 0x0002, type: bool, state_interface: unknown, factor: 1.0}  #DMC__FeedbackStatus__Latch extern valid
      - {index: 0x6030, sub_index: 0x0003, type: bool, state_interface: unknown, factor: 1.0}  #DMC__FeedbackStatus__Set counter done
      - {index: 0x6030, sub_index: 0x000D, type: bool, state_interface: unknown, factor: 1.0}  #DMC__FeedbackStatus__Status of extern latch
      - {index: 0x6030, sub_index: 0x0011, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Ready to enable
      - {index: 0x6030, sub_index: 0x0012, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Ready
      - {index: 0x6030, sub_index: 0x0013, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Warning
      - {index: 0x6030, sub_index: 0x0014, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Error
      - {index: 0x6030, sub_index: 0x0015, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Moving positive
      - {index: 0x6030, sub_index: 0x0016, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Moving negative
      - {index: 0x6030, sub_index: 0x001C, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Digital input 1
      - {index: 0x6030, sub_index: 0x001D, type: bool, state_interface: unknown, factor: 1.0}  #DMC__DriveStatus__Digital input 2
      - {index: 0x6030, sub_index: 0x0021, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Busy
      - {index: 0x6030, sub_index: 0x0022, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__In-Target
      - {index: 0x6030, sub_index: 0x0023, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Warning
      - {index: 0x6030, sub_index: 0x0024, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Error
      - {index: 0x6030, sub_index: 0x0025, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Calibrated
      - {index: 0x6030, sub_index: 0x0026, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Accelerate
      - {index: 0x6030, sub_index: 0x0027, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Decelerate
      - {index: 0x6030, sub_index: 0x0028, type: bool, state_interface: unknown, factor: 1.0}  #DMC__PositioningStatus__Ready to execute
      - {index: 0x6030, sub_index: 0x0031, type: int32, state_interface: unknown, factor: 1.0}  #DMC__Set position
      - {index: 0x6030, sub_index: 0x0032, type: int16, state_interface: unknown, factor: 1.0}  #DMC__Set velocity
      - {index: 0x6030, sub_index: 0x0033, type: uint32, state_interface: unknown, factor: 1.0}  #DMC__Actual drive time
      - {index: 0x6030, sub_index: 0x0034, type: int32, state_interface: unknown, factor: 1.0}  #DMC__Actual position lag
      - {index: 0x6030, sub_index: 0x0035, type: int16, state_interface: unknown, factor: 1.0}  #DMC__Actual velocity
      - {index: 0x6030, sub_index: 0x0036, type: int32, state_interface: unknown, factor: 1.0}  #DMC__Actual position
      - {index: 0x6030, sub_index: 0x0037, type: uint32, state_interface: unknown, factor: 1.0}  #DMC__Error id
      - {index: 0x6030, sub_index: 0x0038, type: uint8, state_interface: unknown, factor: 1.0}  #DMC__Input cycle counter
      - {index: 0x6030, sub_index: 0x003A, type: int32, state_interface: unknown, factor: 1.0}  #DMC__Latch value
      - {index: 0x6030, sub_index: 0x003B, type: int16, state_interface: unknown, factor: 1.0}  #DMC__Cyclic info data 1
      - {index: 0x6030, sub_index: 0x003C, type: int16, state_interface: unknown, factor: 1.0}  #DMC__Cyclic info data 2

sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input,  pdo: tpdo, watchdog: enable}
